In [1]:
import pandas as pd

In [2]:
d=pd.read_csv("test (1).csv")
d

,id,title,Rating,maincateg,platform,actprice1,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
0,2242,Casuals For Men (Blue),3.8,Men,Flipkart,999,27928,3543,14238.0,4295,3457,1962,3976.0,1
1,20532,Women Black Flats Sandal,3.9,Women,Flipkart,499,3015,404,1458.0,657,397,182,321.0,1
2,10648,Women Gold Wedges Sandal,3.9,Women,Flipkart,999,449,52,229.0,70,71,33,46.0,1
3,20677,Men's Height Increasing High Heel Formal Party...,3.9,Men,Flipkart,2999,290,40,141.0,51,49,17,32.0,1
4,12593,Loafers For Men (Tan),3.9,Men,Flipkart,999,2423,326,1265.0,414,293,143,308.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5239,14033,Women Off White Flats Sandal,NaN,Women,Flipkart,699,1235,153,NaN,323,155,62,NaN,1
5240,297,Slip On For Men (Tan),3.9,Men,Flipkart,1993,329,56,350.0,37,60,5,37.0,0
5241,18733,Women Grey Heels Sandal,3.8,Women,Flipkart,999,1280,135,574.0,290,172,94,150.0,0
5242,6162,Womens Casual Comfort Stylish Black High Heel ...,3.9,Women,Flipkart,499,4867,574,2384.0,974,648,328,533.0,0
5243,13574,ZAPATOZ Women's Casual PU Leather Sneaker Shoes,3.9,Women,Amazon,749,8,5,28.0,0,0,0,72.0,1

In [3]:
d.columns

Index(['id', 'title', 'Rating', 'maincateg', 'platform', 'actprice1',
       'norating1', 'noreviews1', 'star_5f', 'star_4f', 'star_3f', 'star_2f',
       'star_1f', 'fulfilled1'],
      dtype='object')

In [4]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5244 entries, 0 to 5243
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          5244 non-null   int64
 1   title       5244 non-null   object
 2   Rating      5041 non-null   float64
 3   maincateg   5177 non-null   object
 4   platform    5244 non-null   object
 5   actprice1   5244 non-null   int64
 6   norating1   5244 non-null   int64
 7   noreviews1  5244 non-null   int64
 8   star_5f     5176 non-null   float64
 9   star_4f     5244 non-null   int64
 10  star_3f     5244 non-null   int64
 11  star_2f     5244 non-null   int64
 12  star_1f     5058 non-null   float64
 13  fulfilled1  5244 non-null   int64
dtypes: float64(3), int64(8), object(3)
memory usage: 573.7+ KB

In [5]:
d.isnull().sum()

id              0
title           0
Rating        203
maincateg      67
platform        0
actprice1       0
norating1       0
noreviews1      0
star_5f        68
star_4f         0
star_3f         0
star_2f         0
star_1f       186
fulfilled1      0
dtype: int64

In [6]:
ns=d.select_dtypes("int64","float64")
ns

,id,actprice1,norating1,noreviews1,star_4f,star_3f,star_2f,fulfilled1
0,2242,999,27928,3543,4295,3457,1962,1
1,20532,499,3015,404,657,397,182,1
2,10648,999,449,52,70,71,33,1
3,20677,2999,290,40,51,49,17,1
4,12593,999,2423,326,414,293,143,0
...,...,...,...,...,...,...,...,...
5239,14033,699,1235,153,323,155,62,1
5240,297,1993,329,56,37,60,5,0
5241,18733,999,1280,135,290,172,94,0
5242,6162,499,4867,574,974,648,328,0
5243,13574,749,8,5,0,0,0,1

In [7]:
ns.corr()

,id,actprice1,norating1,noreviews1,star_4f,star_3f,star_2f,fulfilled1
id,1.000000,0.017346,-0.005400,-0.006166,-0.004093,-0.007262,-0.002321,-0.008975
actprice1,0.017346,1.000000,-0.067529,-0.064513,-0.059661,-0.070007,-0.081037,0.236018
norating1,-0.005400,-0.067529,1.000000,0.995372,0.980808,0.987718,0.967278,0.103945
noreviews1,-0.006166,-0.064513,0.995372,1.000000,0.985507,0.985558,0.948874,0.097584
star_4f,-0.004093,-0.059661,0.980808,0.985507,1.000000,0.956674,0.912031,0.101222
star_3f,-0.007262,-0.070007,0.987718,0.985558,0.956674,1.000000,0.967236,0.097155
star_2f,-0.002321,-0.081037,0.967278,0.948874,0.912031,0.967236,1.000000,0.102702
fulfilled1,-0.008975,0.236018,0.103945,0.097584,0.101222,0.097155,0.102702,1.000000

In [8]:
x=d[["actprice1","norating1","fulfilled1"]]

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
d=StandardScaler()

In [11]:
x=d.fit_transform(x)
x

array([[-0.29649007,  1.93628654,  0.80886258],
       [-0.68696011,  0.00205123,  0.80886258],
       [-0.29649007, -0.19717198,  0.80886258],
       ...,
       [-0.29649007, -0.13265347, -1.23630395],
       [-0.68696011,  0.14583977, -1.23630395],
       [-0.49172509, -0.23141104,  0.80886258]], shape=(5244, 3))

In [12]:
from sklearn.neighbors import NearestNeighbors

In [13]:
model=NearestNeighbors(n_neighbors=6,metric="euclidean")
model.fit(x)

NearestNeighbors(metric='euclidean', n_neighbors=6)

In [14]:
x=["actprice1","Rating","fulfilled1"]

In [15]:
#d["platform"].unique()

In [17]:
def rec(plat):
    d_index =d[d["platform"] ==plat].index[0]
    
    query_point =s.loc[[s_index], x].values
   
    distances, indices = model.kneighbors(query_point)
    
    return s.iloc[indices[0]]["platform"]

# 3. Test it
print(rec("Amazon"))

TypeError: 'StandardScaler' object is not subscriptable