In [1]:
import pandas as pd

In [2]:
s=pd.read_csv("Tamil_songs.csv")
s

,song_name,singer,singer_id,duration,language,released_date,danceability,acousticness,energy,liveness,loudness,speechiness,tempo,mode,key,Valence,time_signature,popularity,Stream
0,En Iniya Pon Nilave,K J Yesudas,/artist/k-j-yesudas,04:18,Tamil,04-04-2002,0.80,0.849,0.467,0.170,-3.264,0.0200,162.040,1,0,0.0600,4,46,7160839
1,Andhi Mazhai Pozhigirathu,S. Janaki|S. P. Balasubrahmanyam|T.V. Gopalakr...,/artist/s-janaki|/artist/s-p-balasubrahamanyam...,04:36,Tamil,01-03-2023,0.10,0.360,0.039,0.180,-4.747,0.0677,151.990,1,5,0.0688,4,53,4329874
2,Madai Thiranthu,S. P. Balasubrahmanyam,/artist/s-p-balasubrahamanyam,04:21,Tamil,06-12-2013,0.82,0.565,0.618,0.292,-8.403,0.0100,128.026,0,5,0.0834,4,47,7299039
3,Ilamai Ennum Poonkaatru,S. P. Balasubrahmanyam,/artist/s-p-balasubrahamanyam,04:08,Tamil,07-07-2002,0.02,0.200,0.378,0.670,-9.441,0.0210,169.464,1,5,0.0200,4,51,8531979
4,Ithu Oru Ponmalai,S. P. Balasubrahmanyam,/artist/s-p-balasubrahamanyam,04:20,Tamil,04-03-2020,0.29,0.663,0.014,0.765,-12.583,0.0950,145.046,1,6,0.0190,4,77,4102936
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4672,Pottane Oru Polu - Dialogues,T.M. Soundararajan,/artist/tm-soundararajan,03:02,Tamil,01-12-2011,0.39,0.714,0.664,0.610,-8.346,0.0800,111.791,1,1,0.0752,4,49,2465126
4673,Manmatha Oodangale,S. P. Balasubrahmanyam|S. Janaki,/artist/s-p-balasubrahamanyam|/artist/s-janaki,04:15,Tamil,09-03-2010,0.68,0.100,0.859,0.800,-5.642,0.0679,120.078,0,11,0.0837,4,32,8466540
4674,Angalamma,P Suhseela|Malaysia Vasudevan,/artist/p-suhseela|/artist/malaysia-vasudevan,05:29,Tamil,01-06-2004,0.96,0.670,0.438,0.505,-5.733,0.0793,140.042,1,10,0.0102,4,72,3917101
4675,Aalam Padaiththavane,Nellai S.M.Abul Barakath,/artist/nellai-smabul-barakath,07:50,Tamil,12-08-2002,0.91,0.680,0.690,0.200,-7.410,0.0964,159.806,1,5,0.0400,4,53,6000742
4676,Nadakattum Raja,S. P. Balasubrahmanyam,/artist/s-p-balasubrahamanyam,04:25,Tamil,04-12-2016,0.22,0.049,0.139,0.016,-9.530,0.0863,110.005,0,11,0.0455,4,96,8620930

In [3]:
s.columns

Index(['song_name', 'singer', 'singer_id', 'duration', 'language',
       'released_date', 'danceability', 'acousticness', 'energy', 'liveness',
       'loudness', 'speechiness', 'tempo', 'mode', 'key', 'Valence',
       'time_signature', 'popularity', 'Stream'],
      dtype='object')

In [4]:
ns=s.select_dtypes("int64","float64")
ns

      mode  key  time_signature  popularity   Stream
0        1    0               4          46  7160839
1        1    5               4          53  4329874
2        0    5               4          47  7299039
3        1    5               4          51  8531979
4        1    6               4          77  4102936
...    ...  ...             ...         ...      ...
4672     1    1               4          49  2465126
4673     0   11               4          32  8466540
4674     1   10               4          72  3917101
4675     1    5               4          53  6000742
4676     0   11               4          96  8620930

[4677 rows x 5 columns]

In [5]:
ns.corr()

                    mode       key  time_signature  popularity    Stream
mode            1.000000 -0.267131       -0.011557   -0.004634 -0.018890
key            -0.267131  1.000000        0.011907   -0.010061  0.004223
time_signature -0.011557  0.011907        1.000000    0.019862 -0.008482
popularity     -0.004634 -0.010061        0.019862    1.000000  0.013524
Stream         -0.018890  0.004223       -0.008482    0.013524  1.000000

In [6]:
x=s[["danceability","tempo","loudness","Valence","energy"]]

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
ss=StandardScaler()

In [9]:
x=ss.fit_transform(x)
x

array([[ 1.03137762,  0.32384745,  1.35638702,  0.35573566, -0.11425995],
       [-1.39786806, -0.05048221,  0.929722  ,  0.66034681, -1.60449986],
       [ 1.10078464, -0.94306288, -0.12212379,  1.16572439,  0.41150227],
       ...,
       [ 1.58663378, -0.49550616,  0.64604586, -1.36808651, -0.21523415],
       [ 1.41311623,  0.24063825,  0.16356627, -0.3365624 ,  0.66219683],
       [-0.98142594, -1.61428624, -0.44636619, -0.14618043, -1.25631297]],
      shape=(4677, 5))

In [10]:
from sklearn.neighbors import NearestNeighbors

In [15]:
model=NearestNeighbors(n_neighbors=6,metric="euclidean")
model.fit(x)

NearestNeighbors(metric='euclidean', n_neighbors=6)

In [16]:
#s["song_name"].unique()

In [18]:
def rec(song):
    s_index = s[s["song_name"] == song].index[0]
    
    query_point = s.loc[[s_index], x].values
   
    distances, indices = model.kneighbors(query_point)
    
    return s.iloc[indices[0]]["song_name"]

print(rec("Andhi Mazhai Pozhigirathu"))

KeyError: "None of [Index([  (1.0313776242248047, 0.32384744631260587, 1.3563870194691579, 0.35573566310459886, -0.11425994579908846),\n           (-1.397868056643106, -0.05048220683666488, 0.9297220000014323, 0.6603468093534279, -1.604499861768051),\n         (1.1007846436781734, -0.9430628842564798, -0.12212379310308853, 1.1657243929026215, 0.41150226754510144),\n           (-1.6754961344565815, 0.6003671821315306, -0.4207605363313415, -1.02886045620826, -0.4241462834655317),\n        (-0.7385013718361018, -0.3091235114604009, -1.3247264777794825, -1.0634753591910815, -1.6915465858316585),\n            (0.4067144491444848, 0.7648487491272701, 1.1314024980775452, -1.7211585158646896, -1.559235565254975),\n          (-1.085536469102946, 0.3279073400631804, -0.25101518131720935, 0.21727605117331308, 1.4804360390462032),\n            (0.6149355075045916, 0.6813415767530747, 1.6348844832889544, -1.5134690979677607, 1.4769541700836588),\n        (-0.9467224301962084, -1.205019147997657, -1.0292544784582724, -0.2673325905861875, 0.045906026477949516),\n           (0.6496390172312757, 0.43484270664940544, -0.2748946126158071, -1.02886045620826, 0.49506712264616487),\n       ...\n          (-0.6343908426560483, -0.8687929013331318, 0.9556153592408761, 0.8714977175486387, -0.4833380558287849),\n        (1.6560407993051245, 0.24678395851501006, -0.3272567390777938, -0.3365623965518305, -0.03765882862311388),\n         (-0.7037978621094173, -1.164531950686885, -0.4233498722552854, 0.009586633276384279, 1.0417205497656208),\n           (1.1007846436781734, 1.0594703965313232, 1.6501327948410711, -0.6827114263800453, -0.4833380558287849),\n          (-1.0161294496495772, 0.9935436814990642, -0.2124628464495928, -1.5480840009505823, 1.3446431495069753),\n        (-0.39146627456925726, -1.5477635727020942, -0.10572466558477395, 0.8818821884434854, 0.5716682398221397),\n             (0.6149355075045916, -1.2390999074634859, 0.6722269275647402, 1.1761088637974677, 1.250632687518279),\n          (1.5866337798517556, -0.4955061566702467, 0.6460458643337471, -1.3680865054399105, -0.2152341457128734),\n           (1.4131162312183336, 0.2406382477916641, 0.16356627050544248, -0.3365623965518305, 0.6621968328482912),\n       (-0.9814259399228928, -1.6142862354408605, -0.44636619157923557, -0.1461804301463125, -1.2563129655136205)],\n      dtype='object', length=4677)] are in the [columns]"